secondSite/urls.py
from django.contrib import admin
from django.urls import path
from app01 import views

urlpatterns = [
    # path('admin/', admin.site.urls),

    # 部门
    path('depart/list/', views.depart_list),
    path(
        'depart/list/<int:page>',
        views.depart_list,
        name="departs-by-page",
    ),
    path('depart/<int:cur_page>/delete/', views.depart_delete),

    # 用户
    path('user/list/', views.user_list),
    path(
        'user/list/<int:page>',
        views.user_list,
        name="users-by-page",
    ),
    path('user/<int:cur_page>/delete/', views.user_delete),

    # 靓号
    path('number/list/', views.number_list),
    path(
        'number/list/<int:page>',
        views.number_list,
        name="nums-by-page",
    ),
    path('number/<int:cur_page>/delete/', views.number_delete),
    path('number/<int:cur_page>/delete/<str:q>', views.number_delete),

    # 管理员
    path('admin/list/', views.admin_list),
    path(
        'admin/list/<int:page>',
        views.admin_list,
        name="admins-by-page",
    ),
    path('admin/<int:cur_page>/delete/', views.admin_delete),
    path('admin/<int:cur_page>/delete/<str:q>', views.admin_delete),
    path('admin/<int:nid>/reset/', views.admin_reset),

    # login
    path('login/', views.login),
    # sign out
    path('signout/', views.sign_out),

    # order
    path('order/list/', views.order_list),
    path(
        'order/list/<int:page>',
        views.order_list,
        name="orders-by-page",
    ),
    path('order/add/', views.order_add),
    path('order/delete/', views.order_delete),
    path('order/detail/', views.order_detail),
    path('order/edit/', views.order_edit),

    # charts
    path('chart/list/', views.chart_list),
    path('chart/bar/', views.chart_bar),
    path('chart/line/', views.chart_line),
    path('chart/pie/', views.chart_pie),

]

app01/models.py
from django.db import models


class Admin(models.Model):
    """ 管理员 """
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)

    def __str__(self):
        return self.username


class Department(models.Model):
    """部门表"""
    title = models.CharField(verbose_name="部门表", max_length=32)

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """员工表"""
    name = models.CharField(verbose_name="姓名", max_length=16)
    password = models.CharField(verbose_name="密码", max_length=64)
    age = models.IntegerField(verbose_name="年龄")
    deposit = models.DecimalField(verbose_name="存款", max_digits=10, decimal_places=2, default=0)
    create_time = models.DateTimeField(verbose_name="入职时间")

    # 无约束
    # depart_id = models.IntegerField(verbose_name='部门ID')
    # 1. 有约束
    #     - to, 与哪张表关联
    #     - to_field, 与表中哪一列关联
    # 2. Django
    #     - 写的depart
    #     - 生成的数据列depart_id
    # 3. 如果部门表被删除
    # #### 3.1 级联删除
    # depart = models.ForeignKey(to="Department", to_field="id", on_delete=models.CASCADE)
    # #### 3.2 depart_id列置空
    depart = models.ForeignKey(verbose_name="部门", to="Department", to_field="id",
                               null=True, blank=True, on_delete=models.SET_NULL)

    # 在Django中做的约束
    gender_choices = (
        (1, "male"),
        (2, "female"),
    )
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices)


class PrettyNum(models.Model):
    """ 靓号表 """
    mobile = models.CharField(verbose_name="手机号", max_length=32)
    price = models.IntegerField(verbose_name="价格", default=0)

    level_choices = (
        (1, "1级"),
        (2, "2级"),
        (3, "3级"),
        (4, "4级"),
    )
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1)

    status_choices = (
        (1, "已占用"),
        (2, "未使用"),
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=2)


class Order(models.Model):
    """ 订单 """
    order_id = models.CharField(verbose_name="order number", max_length=64)
    product = models.CharField(verbose_name="product", max_length=64)
    price = models.IntegerField(verbose_name="price")

    status_choices = (
        (1, "Pending"),
        (2, "Ordered"),
    )
    status = models.SmallIntegerField(verbose_name="status", choices=status_choices, default=1)
    customer = models.ForeignKey(verbose_name="name", to="Admin", on_delete=models.CASCADE)

app01/views.py
import random

from django.shortcuts import render, redirect, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator
from django.http import JsonResponse
from datetime import datetime
from app01 import models
from app01.utils.form import UserModelForm, NumberModelForm, AdminPwdResetModelForm, \
    NumberEditModelForm, AdminModelForm, AdminEditModelForm, LoginForm, OrderModelForm


def depart_list(request, page=1):
    queryset = models.Department.objects.all()

    # 分页
    paginator = Paginator(queryset, per_page=5)
    page_object = paginator.get_page(page)
    page_object.adjusted_elided_pages = paginator.get_elided_page_range(page, on_each_side=1)
    queryset = paginator.page(page).object_list

    if request.method == "POST":
        if 'add_depart' in request.POST:
            title = request.POST.get("title")
            models.Department.objects.create(title=title)
            # 添加部门则跳转到最后一页
            return redirect("/depart/list/" + str(paginator.num_pages))
        elif 'edit_depart' in request.POST:
            editing_id = request.POST.get("depart_id_editing")
            new_depart_title = request.POST.get("new_depart_title")
            models.Department.objects.filter(id=editing_id).update(title=new_depart_title)
            # 编辑部门则保持在当前页
            return redirect("/depart/list/" + str(page))
    return render(request, "depart_list.html", {"queryset": queryset, "page_obj": page_object})


def depart_delete(request, cur_page):
    nid = request.GET.get("nid")
    models.Department.objects.filter(id=nid).delete()
    return redirect("/depart/list/" + str(cur_page))


def user_list(request, page=1):
    form = UserModelForm()
    queryset = models.UserInfo.objects.all()

    # 分页
    paginator = Paginator(queryset, per_page=5)
    page_object = paginator.get_page(page)
    page_object.adjusted_elided_pages = paginator.get_elided_page_range(page, on_each_side=1)
    queryset = paginator.page(page).object_list

    context = {
        'queryset': queryset,
        'gender_choice': models.UserInfo.gender_choices,
        'depart_list': models.Department.objects.all(),
        'page_obj': page_object,
        'form': form
    }

    if request.method == "POST":
        # 获取用户提交数据
        if 'add_user1' in request.POST:
            user_name = request.POST.get("user_name")
            pwd = request.POST.get("pwd")
            age = request.POST.get("age")
            deposit = request.POST.get("deposit")
            create_time = request.POST.get("time")
            gender_id = request.POST.get("gender")
            depart_id = request.POST.get("dp")
            # 添加到数据库中
            models.UserInfo.objects.create(name=user_name, password=pwd, age=age,
                                           deposit=deposit, create_time=create_time,
                                           gender=gender_id, depart_id=depart_id)
            return redirect("/user/list/" + str(paginator.num_pages))
        elif 'add_user2' in request.POST:
            context['form'] = UserModelForm(data=request.POST)
            if context['form'].is_valid():
                context['form'].save()
            else:
                return render(request, "user_list.html", context)
            return redirect("/user/list/" + str(paginator.num_pages))
        elif 'edit_user' in request.POST:
            editing_id = request.POST.get("user_id_editing")
            row_obj = models.UserInfo.objects.filter(id=editing_id).first()
            context['form'] = UserModelForm(data=request.POST, instance=row_obj)
            if context['form'].is_valid():
                context['form'].save()
            else:
                return render(request, "user_list.html", context)
            return redirect("/user/list/" + str(page))

    # 获取用户信息
    # queryset = models.UserInfo.objects.all()
    """
    for obj in queryset:
        # .get_gender_display()找到gender元组编号对应的值; .depart.id/.depart.title找到连表里的内容
        print(obj.get_gender_display(), obj.depart_id, obj.depart.id, obj.depart.title)
    """

    return render(request, "user_list.html", context)


def user_delete(request, cur_page):
    nid = request.GET.get("nid")
    models.UserInfo.objects.filter(id=nid).delete()
    return redirect("/user/list/" + str(cur_page))


def number_list(request, page=1):
    form = NumberModelForm()
    # 搜索号码
    data_dict = {}
    search_data = request.GET.get("query", "")
    if search_data:
        data_dict["mobile__contains"] = search_data
    queryset = models.PrettyNum.objects.filter(**data_dict).order_by("-level")

    # 分页
    paginator = Paginator(queryset, per_page=5)
    page_object = paginator.get_page(page)
    page_object.adjusted_elided_pages = paginator.get_elided_page_range(page, on_each_side=1)
    queryset = paginator.page(page).object_list

    context = {
        "queryset": queryset,
        "form": form,
        "search_data": search_data,
        "page_obj": page_object,
    }

    if request.method == "POST":
        if 'add_number' in request.POST:
            context['form'] = NumberModelForm(data=request.POST)
            if context['form'].is_valid():
                context['form'].save()
            else:
                return render(request, "number_list.html", context)
            return redirect("/number/list/" + str(paginator.num_pages))
        if 'edit_number' in request.POST:
            editing_id = request.POST.get("number_id_editing")
            row_obj = models.PrettyNum.objects.filter(id=editing_id).first()
            context['form'] = NumberEditModelForm(data=request.POST, instance=row_obj)
            if context['form'].is_valid():
                context['form'].save()
            else:
                return render(request, "number_list.html", context)
            return redirect("/number/list/" + str(page) + "?query=" + search_data)

    return render(request, "number_list.html", context)


def number_delete(request, cur_page, q=""):
    nid = request.GET.get("nid")
    models.PrettyNum.objects.filter(id=nid).delete()
    return redirect("/number/list/" + str(cur_page) + "?query=" + q)


def admin_list(request, page=1):
    """ 管理员列表 """
    form = AdminModelForm()
    # 搜索号码
    data_dict = {}
    search_data = request.GET.get("query", "")
    if search_data:
        data_dict["username__contains"] = search_data
    queryset = models.Admin.objects.filter(**data_dict).all()

    # 分页
    paginator = Paginator(queryset, per_page=5)
    page_object = paginator.get_page(page)
    page_object.adjusted_elided_pages = paginator.get_elided_page_range(page, on_each_side=1)
    queryset = paginator.page(page).object_list

    context = {
        "queryset": queryset,
        "form": form,
        "search_data": search_data,
        "page_obj": page_object,
    }

    if request.method == "POST":
        if 'add_admin' in request.POST:
            context['form'] = AdminModelForm(data=request.POST)
            if context['form'].is_valid():
                context['form'].save()
            else:
                return render(request, "admin_list.html", context)
            return redirect("/admin/list/" + str(paginator.num_pages))
        if 'edit_admin' in request.POST:
            editing_id = request.POST.get("admin_id_editing")
            row_obj = models.Admin.objects.filter(id=editing_id).first()
            context['form'] = AdminEditModelForm(data=request.POST, instance=row_obj)
            if context['form'].is_valid():
                context['form'].save()
            else:
                return render(request, "admin_list.html", context)
            return redirect("/admin/list/" + str(page) + "?query=" + search_data)

    return render(request, "admin_list.html", context)


def admin_delete(request, cur_page, q=""):
    nid = request.GET.get("nid")
    models.Admin.objects.filter(id=nid).delete()
    return redirect("/admin/list/" + str(cur_page) + "?query=" + q)


def admin_reset(request, nid):
    """ 编辑管理员密码 """
    row_obj = models.Admin.objects.filter(id=nid).first()
    if not row_obj:
        return redirect("/admin/list/")

    title = "重置密码 - {}".format(row_obj.username)
    if request.method == 'GET':
        form = AdminPwdResetModelForm()
        return render(request, "admin_edit.html", {'form': form, 'title': title})

    form = AdminPwdResetModelForm(data=request.POST, instance=row_obj)
    if form.is_valid():
        form.save()
        return redirect("/admin/list/")
    return render(request, "admin_edit.html", {'form': form, 'title': title})


def login(request):
    if request.method == 'GET':
        form = LoginForm()
        return render(request, "login.html", {'form': form})
    form = LoginForm(data=request.POST)
    if form.is_valid():
        form.cleaned_data.pop("captcha")
        # 获取到的用户名、密码去数据库校验
        admin_obj = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_obj:
            form.add_error("username", "Incorrect username or password")
            return render(request, "login.html", {'form': form})
        # 用户名密码正确，跳转到admin_list
        request.session["info"] = {'id': admin_obj.id, 'name': admin_obj.username}
        return redirect("/admin/list/")
    return render(request, "login.html", {'form': form})


def sign_out(request):
    request.session.clear()
    return redirect("/login/")


def order_list(request, page=1):
    form = OrderModelForm()
    queryset = models.Order.objects.all().order_by("-id")
    # 分页
    paginator = Paginator(queryset, per_page=5)
    page_object = paginator.get_page(page)
    page_object.adjusted_elided_pages = paginator.get_elided_page_range(page, on_each_side=1)
    queryset = paginator.page(page).object_list

    context = {
        "queryset": queryset,
        "form": form,
        "page_obj": page_object,
    }
    return render(request, "order_list.html", context)


@csrf_exempt
def order_add(request):
    """ 创建订单 """

app01/templates/admin_edit.html
{% extends 'layout.html' %}

{% block title %}
    <title>edit admins</title>
{% endblock %}


{% block content %}
    <div class="container">
        <div class="card">
            <div class="card-body">
                <i class="bi bi-list-ul"></i>
                {{ title }}
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="mb-3">
                            <label class="col-form-label">{{ field.label }}:</label>
                            {{ field }}
                            <!--<input type="text" class="form-control" placeholder="name" name="user_name">-->
                            <span style="color: red">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    <div class="modal-footer">
                        <button type="submit" name="edit_admin" class="btn btn-primary">
                            Save
                        </button>
                    </div>
                </form>
            </div>
        </div>

    </div>
{% endblock %}

app01/templates/chart_list.html
{% extends "layout.html" %}
{% block title %}
    <title>charts</title>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="card" style="margin-bottom: 20px">
            <div class="card-header">
                Bar Chart
            </div>
            <div class="card-body">
                <div id="bar" style="width: 100%"></div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8">
                <div class="card">
                    <div class="card-header">
                        Line Chart
                    </div>
                    <div class="card-body">
                        <div id="line" style=""></div>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card">
                    <div class="card-header">
                        Pie Chart
                    </div>
                    <div class="card-body">
                        <div id="pie" style=""></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script type="text/javascript">
        $(function () {
            barChartPlot();
            lineChartPlot();
            pieChartPlot();
        })

        function barChartPlot() {
            var option = {
                chart: {
                    type: 'column'
                },
                title: {
                    text: 'Bar Chart Title'
                },
                subtitle: {
                    text: ''
                },
                xAxis: {
                    categories: [],     //后台获取
                    crosshair: true
                },
                yAxis: {
                    min: 0,
                    title: {
                        text: 'Rainfall (mm)'
                    }
                },
                tooltip: {
                    headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                    pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                        '<td style="padding:0"><b>{point.y:.1f} (单位)</b></td></tr>',
                    footerFormat: '</table>',
                    shared: true,
                    useHTML: true
                },
                plotOptions: {
                    column: {
                        pointPadding: 0.2,
                        borderWidth: 0
                    }
                },
                series: []      //后台获取
            }
            $.ajax({
                url: "/chart/bar/",
                type: "get",
                dataType: "JSON",
                success: function (res) {
                    if (res.status) {
                        option.xAxis.categories = res.data.x_axis;
                        option.series = res.data.data_series;

                        Highcharts.chart('bar', option);

                    }
                }
            })
        }

        function lineChartPlot() {
            var option = {
                title: {
                    text: 'U.S Solar Employment Growth by Job Category, 2010-2020',
                    align: 'left'
                },
                subtitle: {
                    text: '',
                    align: 'left'
                },
                yAxis: {
                    title: {
                        text: 'Number of Employees'
                    }
                },
                xAxis: {
                    accessibility: {
                        // rangeDescription: 'Range: 2010 to 2020'
                        // categories: [...Array(2010,2019).keys()],
                    }
                },
                legend: {
                    /*
                    layout: 'vertical',
                    align: 'right',
                    verticalAlign: 'middle'
                    */
                    layout: 'horizontal',
                    align: 'center',
                    verticalAlign: 'bottom'
                },
                plotOptions: {
                    series: {
                        label: {
                            connectorAllowed: false
                        },
                        pointStart: null        //后台获取
                    }
                },
                series: [],
            }
            $.ajax({
                url: "/chart/line/",
                type: "get",
                dataType: "JSON",
                success: function (res) {
                    if (res.status) {
                        option.plotOptions.series.pointStart = res.data.x_start;
                        option.series = res.data.data_series;
                        Highcharts.chart('line', option);
                    }
                }
            })
        }

        function pieChartPlot() {
            var option = {
                chart: {
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    type: 'pie'
                },
                title: {
                    text: 'Browser market shares in May, 2020',
                    align: 'left'
                },
                tooltip: {
                    pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
                },
                accessibility: {
                    point: {
                        valueSuffix: '%'
                    }
                },
                /* plotOptions: {
                    pie: {
                        allowPointSelect: true,
                        cursor: 'pointer',
                        dataLabels: {
                            enabled: true,
                            format: '<b>{point.name}</b>: {point.percentage:.1f} %'
                        }
                    }
                },*/
                series: [{
                    name: 'Brands',
                    colorByPoint: true,
                    data: []
                }]
            }
            $.ajax({
                url: "/chart/pie/",
                type: "get",
                dataType: "JSON",
                success: function (res) {
                    if (res.status) {
                        option.series[0].data = res.data.data_series;
                        Highcharts.chart('pie', option);
                    }
                }
            })
        }

    </script>

{% endblock %}

app01/templates/number_list.html
{% extends 'layout.html' %}

{% block title %}
    <title>pretty num</title>
{% endblock %}


{% block content %}
    <div class="container">

        <div style="margin-bottom: 10px" class="clearfix">
            <button type="button" class="btn btn-success btn-sm" data-bs-toggle="modal"
                    data-bs-target="#addingModal">新建靓号
            </button>
            <div class="modal fade" id="addingModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="exampleModalLabel">Add Mobile</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <form method="post" novalidate>
                                {% csrf_token %}
                                {% for field in form %}
                                    <div class="mb-3">
                                        <label class="col-form-label">{{ field.label }}:</label>
                                        {{ field }}
                                        <!--<input type="text" class="form-control" placeholder="name" name="user_name">-->
                                        <span style="color: red">{{ field.errors.0 }}</span>
                                    </div>
                                {% endfor %}
                                <div class="modal-footer">
                                    <button type="submit" name="add_number" class="btn btn-primary">Save</button>
                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
            <div style="float: right; width: 300px">
                <form method="get" action="/number/list/1?query={{ search_data }}">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Search number"
                               name="query" value={{ search_data }}>
                        <button class="btn btn-outline-secondary" type="submit" id="button-addon2">
                            <i class="bi bi-search"></i>
                        </button>
                    </div>
                </form>
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                <i class="bi bi-list-ul"></i>
                靓号列表
            </div>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Number</th>
                    <th scope="col">Price</th>
                    <th scope="col">Level</th>
                    <th scope="col">Status</th>
                    <th scope="col">Operation</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th scope="row">{{ obj.id }}</th>
                        <td>{{ obj.mobile }}</td>
                        <td>{{ obj.price }}</td>
                        <td>{{ obj.get_level_display }}</td>
                        <td>{{ obj.get_status_display }}</td>
                        <td>
                            <button type="button" class="btn btn-primary btn-sm"
                                    data-bs-toggle="modal" data-bs-id="{{ obj.id }}"
                                    data-bs-target="#editModal">编辑
                            </button>
                            <div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                                 aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h1 class="modal-title fs-5" id="exampleModalLabel">Edit Number</h1>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                    aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <form method="post">
                                                {% csrf_token %}
                                                {% for field in form %}
                                                    <div class="mb-3">
                                                        <label class="col-form-label">{{ field.label }}:</label>
                                                        {{ field }}
                                                        <!--<input type="text" class="form-control" placeholder="name" name="user_name">-->
                                                        <span style="color: red">{{ field.errors.0 }}</span>
                                                    </div>
                                                {% endfor %}
                                                <div class="mb-3">
                                                    <input type="hidden" name="number_id_editing">
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="submit" name="edit_number" class="btn btn-primary">
                                                        Save
                                                    </button>
                                                </div>
                                            </form>
                                        </div>

                                    </div>
                                </div>
                            </div>
                            {#                            <a class="btn btn-primary btn-sm" href="#">编辑</a>#}
                            <a class="btn btn-danger btn-sm"
                               href="/number/{{ page_obj.number }}/delete/{{ search_data }}?nid={{ obj.id }}">
                                删除
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>

            </table>
        </div>

    </div>
{% endblock %}

{% block pagination %}
{#    前一页#}
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="{% url 'nums-by-page' page_obj.previous_page_number %}?query={{ search_data }}">
                Previous
            </a>
        </li>
    {% endif %}
{#    中间#}
    {% for page_number in page_obj.adjusted_elided_pages %}
        {% if page_number == page_obj.paginator.ELLIPSIS %}
            {{ page_number }}
        {% else %}
            <li class="page-item {% if page_number == page_obj.number %}active{% endif %}">
                <a
                        class="page-link {% if page_number == page_obj.number %}current{% endif %}"
                        href="{% url 'nums-by-page' page_number %}?query={{ search_data }}">
                    {{ page_number }}
                </a>
            </li>
        {% endif %}
    {% endfor %}
{#    后一页#}
    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="{% url 'nums-by-page' page_obj.next_page_number %}?query={{ search_data }}">
                Next
            </a>
        </li>
    {% endif %}
{% endblock %}


{% block script %}
    <script type="text/javascript">
        const editModal = document.getElementById('editModal')
        editModal.addEventListener('show.bs.modal', event => {
            // Button that triggered the modal
            const button = event.relatedTarget
            // Extract info from data-bs-* attributes
            const number_id = button.getAttribute('data-bs-id')
            // If necessary, you could initiate an AJAX request here
            // and then do the updating in a callback.
            //
            // Update the modal's content.
            // const modalBodyInput = editModal.querySelector('.modal-body input[type="text"]')
            const modalHiddenInput = editModal.querySelector('.modal-body input[name="number_id_editing"]')

            modalHiddenInput.value = number_id
        })
    </script>
{% endblock %}